### ISSUE TITLE
Thanks so much for choosing beartype, @albanie.

### ISSUE THREAD

**Issue by leycec** [albanie/slurm_gpustat#9]
Obviously, *this isn't an issue.* I just noticed you embraced @beartype across both this and  [yaspi](https://github.com/albanie/yaspi) and... I just wanted to express my gratitude. This makes your popular SLURM work my first actual downstream consumer, which is both exciting and frightening. I'll try not to break everything.

Relatedly, I couldn't help but obsessively notice in the `slurm_gpustat` module:

```
from beartype.cave import NoneType
...
@beartype
def node_states(partition: (str, NoneType) = None) -> dict:
```

**This is absolutely fine.** However, the `beartype.cave.NoteTypeOr` type hint factory provides an efficient alternative to the above that internally caches the tuple unions it creates for reuse across multiple callables: e.g.,

```
from beartype.cave import NoneTypeOr
...
@beartype
def node_states(partition: NoneTypeOr[str] = None) -> dict:
```

Of course, we're also now [fully PEP 484-compliant](https://www.python.org/dev/peps/pep-0484). The `typing.Optional` singleton object thus provides *yet another* efficient alternative to the above that also internally caches the strange objects it creates: e.g.,

```
from typing import Optional
...
@beartype
def node_states(partition: Optional[str] = None) -> dict:
```

Apologies for polluting this issue tracker with pablum. Please close this before someone laughs at me.

We now return to your regularly scheduled video NLP. Man, I wish *I* could do video NLP. Then people would probably pay me bucketloads of money and I could hygienically bath in dollar bills. :money_with_wings:

**Comment by albanie** [comment]
Thank you! I will upgrade to the latest and greatest syntax.

**Comment by leycec** [comment]
Oh, thank you. Now I'll have to begin reading your many awesome papers. There goes the weekend.
